# Generated by Django 3.0.7 on 2020-09-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShippingDetail',
            fields=[
                ('user_shipping_detail_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('receiver', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
