# Generated by Django 3.0.7 on 2020-10-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usershippingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershippingdetail',
            name='additional_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usershippingdetail',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usershippingdetail',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usershippingdetail',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usershippingdetail',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AlterModelTable(
            name='usershippingdetail',
            table='user_shipping_details',
        ),
    ]
